### ISSUE TITLE
Empty line 1 prevents plugin from working

### ISSUE THREAD

**Issue by horihel** [ShredCode/YOURLS-filter-code#1]
Hello,

plugins.php line 1 (before ?php) is empty. This produces an empty line of output, which in turn prevents the plugin from being activated by YOURLS.

**Comment by DylanLWScott** [comment]
Thanks for taking the time to send a note and providing details!  Let me know if you feel this issue can be closed!  Thanks again!

**Comment by horihel** [comment]
thank's a lot! And thanks for this plugin!
