### ISSUE TITLE
Option to change default code

### ISSUE THREAD

**Issue by jsbrain** [ShredCode/YOURLS-filter-code#6]
Hi,

which variable do I have to use to change the default status code for all links, if no explicit status code is selected?

Thank you in advance

**Comment by DylanLWScott** [comment]
Hello!  I am not sure if you need a quick fix or if suggesting the ability to set 
 a default.

 https://github.com/ShredCode/YOURLS-filter-code/blob/bac8d875263e396a62bb0fee021b6c620d100a05/plugin.php#L45

If you need a quick fix: I would modify the line above to not assign the $code variable, but rather the one you wish to use as a default: ie. $status_code = '302';

Hopefully that helps!

**Comment by jsbrain** [comment]
Great, thank you very much!
